name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu image ko use karenge

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub repository ko checkout karenge

    - name: Set up Node.js (v18)
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Node.js version set karenge

    - name: Install dependencies
      run: |
        npm install  # Project dependencies install karenge
        npx playwright install  # Playwright ko install karenge
        sudo chmod -R +x node_modules/.bin/playwright  # Ensure Playwright binary is executable

    - name: Run Playwright tests
      run: npx playwright test  # Playwright tests run karenge
